# Generated by Django 5.1.6 on 2025-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_aiverificationlog_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Security Alert', max_length=150),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('WORTH_CHECKING', 'Worth Checking'), ('DANGEROUS', 'Dangerous'), ('CRITICAL', 'Critical')], default='WORTH_CHECKING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='core_user_set', related_query_name='core_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
