# Generated by Django 5.1.6 on 2025-11-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert_title_incident_severity_level_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
