# Generated by Django 5.1.6 on 2025-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Detection confidence (0-100)'),
        ),
    ]
